{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.imagePullSecret.enabled .Values.image.pullSecret }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.image.pullSecret }}
  labels:
    {{- include "ebrain.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore }}
    kind: SecretStore
  target:
    name: {{ .Values.image.pullSecret }}
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKeys.imagePullDockerConfigJson | quote }}
{{- end }}
