{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.secrets.masterKey.name }}
  labels:
    {{- include "ebrain.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore }}
    kind: SecretStore
  target:
    name: {{ .Values.secrets.masterKey.name }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.secrets.masterKey.ebrainMasterKey }}
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKeys.ebrainMasterKey | quote }}
    - secretKey: {{ .Values.secrets.masterKey.ebrainSecretsKey }}
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKeys.ebrainSecretsKey | quote }}
{{- end }}
