{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecrets.secretStore }}
  labels:
    {{- include "ebrain.labels" . | nindent 4 }}
spec:
  provider:
    {{- if eq .Values.externalSecrets.provider "aws" }}
    aws:
      service: {{ .Values.externalSecrets.aws.service | quote }}
      region: {{ .Values.externalSecrets.aws.region | quote }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ default .Values.serviceAccount.name .Values.externalSecrets.aws.serviceAccountRef.name }}
    {{- else }}
    alibaba:
      regionID: {{ .Values.externalSecrets.alibaba.regionID | quote }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: {{ .Values.externalSecrets.alibaba.authSecretName }}
            key: {{ .Values.externalSecrets.alibaba.accessKeyIdKey }}
          accessKeySecretSecretRef:
            name: {{ .Values.externalSecrets.alibaba.authSecretName }}
            key: {{ .Values.externalSecrets.alibaba.accessKeySecretKey }}
    {{- end }}
{{- end }}
