apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: acr-pull-secret
  labels:
    {{- include "ebrain.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ .Values.externalSecrets.imagePull.secretName }}
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: {{ .Values.externalSecrets.imagePull.dockerConfigJsonRemoteKey }}
