{{- if .Values.certManager.createClusterIssuer }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.certManager.alidns.secretStoreName }}
  namespace: cert-manager
  labels:
    {{- include "ebrain.labels" . | nindent 4 }}
spec:
  provider:
    alibaba:
      regionID: {{ .Values.externalSecrets.secretStore.region }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: {{ .Values.externalSecrets.secretStore.authSecretName }}
            key: {{ .Values.externalSecrets.secretStore.accessKeyIdKey }}
          accessKeySecretSecretRef:
            name: {{ .Values.externalSecrets.secretStore.authSecretName }}
            key: {{ .Values.externalSecrets.secretStore.accessKeySecretKey }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alicloud-dns01-access
  namespace: cert-manager
  labels:
    {{- include "ebrain.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.certManager.alidns.secretStoreName }}
    kind: SecretStore
  target:
    name: {{ .Values.certManager.alidns.accessSecretName }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.certManager.alidns.accessKeyIdKey }}
      remoteRef:
        key: {{ .Values.certManager.alidns.accessKeyIdRemoteKey }}
    - secretKey: {{ .Values.certManager.alidns.accessKeySecretKey }}
      remoteRef:
        key: {{ .Values.certManager.alidns.accessKeySecretRemoteKey }}
{{- end }}
