apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-rds
  labels:
    {{- include "ebrain.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ .Values.externalSecrets.rds.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: {{ .Values.externalSecrets.rds.databaseUrlRemoteKey }}
