apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecrets.secretStore.name }}
  labels:
    {{- include "ebrain.labels" . | nindent 4 }}
spec:
  provider:
    alibaba:
      regionID: {{ .Values.externalSecrets.secretStore.region }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: {{ .Values.externalSecrets.secretStore.authSecretName }}
            key: {{ .Values.externalSecrets.secretStore.accessKeyIdKey }}
          accessKeySecretSecretRef:
            name: {{ .Values.externalSecrets.secretStore.authSecretName }}
            key: {{ .Values.externalSecrets.secretStore.accessKeySecretKey }}
